name: Master Unit + Integration
on:
  push:
    branches: ["master", "main"]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Run unit tests
        run: pytest -q tests/test_unit.py
      - name: Run integration tests
        run: pytest -q tests/test_integration.py
